server:
  port: 10002

spring:
  application:
    name: mao-account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ky-account?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dayi.entity
  configuration:
    # can get id while saving data
    use-generated-keys: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/